src/__tests__/integration.test.tsx, src/hooks/useQuery.ts, src/types/Query.d.ts
The initial value (`[]`) looks like it is placed in the wrong context, so instead of being passed to the `reduce` function as the initial value, it is passed to the `useEffect` function as the second parameter. This caused the returned `data` to be the first `response` from the `Promise.all` chain with all the other responses reduced into it.
=> fix: set initial value for reducer function

services/data/src/context/makeCustomContext.ts
This adds support for a forever-loading state in CustomDataProvider, which is useful for i.e. Storybook demos.  Usage as follows:
```js
<CustomDataProvider options={{ loadForever: true }}>
<...>
</CustomDataProvider>
```
=> feat: support forever-loading CustomDataProvider

runtime/src/index.js
Push had failed, so #13 was accidentally a breaking change
=> fix: don't break app-runtime API, export DataProvider as well

examples/cra/src/App.js, examples/cra/src/components/ConfigConsumer.js, examples/cra/src/components/IndicatorList.js, examples/cra/src/components/SwitchableProvider.js, examples/cra/src/index.js, examples/cra/yarn.lock, services/data/src/components/DataProvider.tsx
There was a bug introduced with #13 which caused the independently exposed DataProvider to ignore its parameters and fall back to the default Config values.  This fixes that issue (one-line change) and also refactors the example to support testing of both configurations.
=> fix: support independent data provider, refactor example

examples/cra/yarn.lock, services/data/src/engine/links/RestAPILink/helpers/networkFetch.test.ts, services/data/src/engine/links/RestAPILink/helpers/networkFetch.ts
This was causing nasty errors, so I'm going to go ahead and merge it to un-break production.
Reason: DHIS2 returns `Content-Type: application/json; charset=UTF-8`, which isn't **exactly** application/json and so caused the link to skip JSON parsing.
=> fix: correctly parse content type

services/data/src/engine/types/FetchError.ts, services/data/src/links/RestAPILink/fetchData.test.ts, services/data/src/links/RestAPILink/fetchData.ts
As discussed on [app-platform](https://dhis2.slack.com/archives/CLJSVA1RV/p1586945462166900). The body of the response that was attached to the error was already parsed, so once it reaches the app, it can't be parsed a second time and the data was lost.
This attaches the parsed data to the error under error.details (it if can be parsed). So error.details will now no longer be the response object.
p.s.: I used a try catch block as I found the synchronous notation easier to read in combination with async/await, but that's a bit subjective, so let me know if you'd like me to use the promise api.
=> fix(parsestatus): add response data to error

services/data/src/engine/types/QueryParameters.ts, services/data/src/links/RestAPILink/queryToResourcePath.test.ts, services/data/src/links/RestAPILink/queryToResourcePath.ts
=> fix: support boolean values for query parameters

services/config/src/__tests__/integration.test.tsx, services/config/src/types.ts
This adds typescript annotations for `systemInfo` and `serverVersion` properties on the Config context object.
Note that these are currently added as Optional properties to avoid causing a breaking change, but eventually we will want them to be required.
=> feat: add explicit support for systemInfo and serverVersion config props

services/data/src/links/RestAPILink/fetchData.test.ts, services/data/src/links/RestAPILink/fetchData.ts, services/data/src/links/RestAPILink/queryToRequestOptions/multipartFormDataMatchers.test.ts, services/data/src/links/RestAPILink/queryToRequestOptions/multipartFormDataMatchers.ts, services/data/src/links/RestAPILink/queryToResourcePath.test.ts
For some more context, see [this Slack thread](https://dhis2.slack.com/archives/CLJSVA1RV/p1611577363000400). This PR contains the following:
- The file `multipartFormDataMatchers.ts` now contains a function that matches the `api/svg.png` or `api/svg.pdf` endpoint, which requires a `FormData` instance as the request body.
- We now try to parse the response data correctly depending on the content-type.
=> feat: add support for svg conversion end-point (libs-105)

docs/hooks/useAlert.md, docs/hooks/useAlerts.md
Two changes intended to make useAlert easier to use for new users/academy participants:
1. Add link to the AlertBar storybook page so users can browse what the different AlertBar props do
2. Move the 'Usage note' in useAlert**s** to the top of the page to point readers in the direction of the plain useAlert hook
=> docs: add to alerts docs

examples/cra/src/components/Alerts.js, examples/cra/yarn.lock, examples/query-playground/yarn.lock, package.json, services/data/package.json, services/data/src/__tests__/integration.test.tsx, services/data/src/__tests__/mutations.test.tsx, services/data/src/react/components/CustomDataProvider.tsx, services/data/src/react/components/DataProvider.tsx, services/data/src/react/hooks/useDataQuery.test.tsx, services/data/src/react/hooks/useDataQuery.ts, yarn.lock
Implements client side caching with react-query (https://react-query.tanstack.com, https://react-query.tanstack.com/reference/useQuery). See https://jira.dhis2.org/browse/LIBS-166 for the related epic.
Todo:
Follow-up:
=> feat(runtime): cache queries with react query

services/data/src/react/components/DataProvider.tsx
This enables [context sharing](https://react-query.tanstack.com/reference/QueryClientProvider) on the QueryClientProvider, which allows react-query to find a provider even if that provider was imported from a different instance of react-query. This is a feature we'll want to use eventually anyway, but it can also help alleviate dependency issues, where the app will crash if multiple copies of react-query are used (and thus no compatible context can be found).
=> feat(data-provider): enable context sharing

services/data/src/react/components/CustomDataProvider.tsx, services/data/src/react/components/DataProvider.tsx, yarn.lock
I've enabled both `retryOnMount` and `refetchOnMount`. This way react-query will trigger a fetch for newly mounted components with an identical query, which is what we currently do.
I've disabled automatic retries on errors, automatic revalidation on window focus and revalidation on reestablished network connections.
The feature that we cannot disable, but that should also be safe to leave enabled is automatic query deduplication. If a query is already fetching, react-query will not create a new fetch for any queries with an identical queryKey. As soon as the promise has settled react-query will allow new fetches again.
=> feat(use-data-query): set conservative defaults for caching

CHANGELOG.md, docs/advanced/CustomDataProvider.md, examples/cra/src/components/Alerts.js, examples/cra/yarn.lock, examples/query-playground/yarn.lock, package.json, runtime/package.json, services/alerts/package.json, services/config/package.json, services/data/package.json, services/data/src/__tests__/integration.test.tsx, services/data/src/__tests__/mutations.test.tsx, services/data/src/react/components/CustomDataProvider.tsx, services/data/src/react/components/DataProvider.tsx, services/data/src/react/hooks/useDataQuery.test.tsx, services/data/src/react/hooks/useDataQuery.ts, services/data/src/types.ts, yarn.lock
https://jira.dhis2.org/browse/LIBS-200
This would not introduce anything new compared to the latest alpha, just promote what's currently on alpha to beta. From there we'd continue the work by:
- Changing SWR to be opt-in
- Not throwing an error on a missing provider, but instead returning an error from the useDataQuery hook (alongside the other required properties)
- I'm also wondering if we should make the contextSharing opt-in, instead of the default (I've read that there were problems with it in certain cases)
@amcgee Do you know if this repo has branch protection enabled for pre-release branches like alpha and beta? Those branches being deleted automatically by github on merge caused some issues for ui a while back. Would be good to enable that before we merge this.
=> feat(use-data-query): add stale-while-revalidate and query deduplication

services/data/src/react/components/DataProvider.tsx
Removes the contextSharing that was enabled by default on the react-query provider. See: https://github.com/dhis2/app-runtime/pull/916
=> fix(use-data-query): drop context sharing

services/data/src/react/hooks/useDataQuery.test.tsx, services/data/src/react/hooks/useDataQuery.ts
This updates the prop we use to show the user whether content is loading or not. Previously we used react-query's `isLoading` and we've now moved to `isFetching`. The difference is that `isLoading` will only be true when there's no data, and a fetch is in progress. `isFetching` will always be true if a fetch is in progress, so it works the same way `loading` does on app-runtime's `master`.
This means that stale-while-revalidate is now opt-in. If a user wants to opt-in to stale-while-revalidate they can switch from using:
```
if (loading) {
// Show spinner
}
```
to:
```
if (loading && !called) {
// Show spinner
}
```
The one thing that seems iffy to me is that we need to manually rerender to get the expected state in the test. I've added a comment and will follow up on that in a separate …
=> fix(use-data-query): make swr opt-in

services/data/src/__tests__/integration.test.tsx, services/data/src/react/hooks/useDataQuery.test.tsx, services/data/src/react/hooks/useDataQuery.ts
Since we don't want to expose any new API for the upcoming changes, users don't really have a way to silence/configure the react-query logger. So for now I'm silencing it by default as otherwise test output will be polluted by the logger. Eventually we could expose API that allows users to control this.
https://react-query.tanstack.com/reference/setLogger
=> fix(logging): silence react-query logger by default

services/offline/src/__tests__/integration.test.tsx, services/offline/src/lib/cacheable-section.tsx
Because `useCacheableSection` sets its section's recording state to `'default'` on mount, it doesn't work to use it inside of the the `<CacheableSection>` component it's controlling: when the section rerenders to record, the recording state is faultily set back to `'default'` instead of `'recording'` when the hook rerenders.
This is a hotfix to fix that behavior: recording state in context isn't set if one exists already, and won't be cleared from context on unmount unless the recording state is `'default'`.  
There is a tiny side effect that in unusual cases where recording states of sections that a user is not viewing are still stored in context after switching to a different section while the recording state is not `'default'`, but that should be both harmless and extremely unusual …
=> fix: allow useCachableSection hook to be used in child of CacheableSection

services/offline/src/lib/__tests__/use-cacheable-section.test.tsx, services/offline/src/lib/global-state-service.tsx
@jenniferarnesen encountered an issue in the Dashboards app where the `isCached` status was not updating when clicking between dashboards. I traced the issue back to the `useGlobalState` hook, which did not update its selected state when the `selector` prop changed, so I update the 'useEffect' hook to do so
=> fix: update state when id arg changes

services/offline/package.json, services/offline/src/lib/__tests__/online-status.test.tsx, services/offline/src/lib/online-status.ts, yarn.lock
@mediremi noticed that the recent fix to `useOnlineStatus` also introduced an issue where the online status state might not update if the component consuming the hook rerenders in the middle of a debounce delay due to the `debouncedFunction.cancel()` call in the `useEffect` cleanup.
~~The `use-debounce` library is used here to handle debouncing and callbacks in a more robust way~~. Instead, `options.debounceDelay` was added as a dependency to the `useCallback` hook.
=> fix: handle debouncing across rerenders

services/offline/src/lib/__tests__/online-status.test.tsx, services/offline/src/lib/online-status.ts
This feature can be used by apps or the header bar to display the 'last online' status. It's stored in `localStorage` so that the value can persist between sessions and be used between apps (although it will only be updated in apps that use PWA or use the most recent UI with the new header bar).
In the tests, I tried mocking the `Date` class and `Date.now()`, but both approaches either had issues with typescript or would make the test fail for mysterious reasons :(
=> feat: track 'last online' time in localStorage

services/data/src/react/hooks/useDataQuery.test.tsx, services/data/src/react/hooks/useDataQuery.ts, services/data/src/types.ts
BREAKING CHANGE: loading will only be set to true when fetching and if there is no data. If there
is data, loading will be false during fetching. This means that stale data will be shown during
fetches by default. If you'd like to opt out of showing stale data during loading you can use the
new `fetching` attribute that is now returned by the useDataQuery hook instead.
=> fix(use-data-query): enable swr by default

CHANGELOG.md
A little cleanup to make the changelog clearer to people who want to upgrade. I've removed all the items that were internal to the alpha/beta and kept only the changes that are user facing.
=> docs(changelog): clean up changelog

docs/hooks/useAlert.md, docs/hooks/useAlerts.md, examples/cra/src/components/Alerts.js, examples/cra/yarn.lock, examples/query-playground/yarn.lock, services/alerts/src/AlertsContext.ts, services/alerts/src/AlertsManagerContext.ts, services/alerts/src/AlertsProvider.tsx, services/alerts/src/__tests__/integration.test.tsx, services/alerts/src/__tests__/useAlert.test.tsx, services/alerts/src/makeAlertsManager.ts, services/alerts/src/types.ts, services/alerts/src/useAlert.ts, services/offline/src/__tests__/integration.test.tsx, services/offline/src/lib/__tests__/offline-provider.test.tsx, services/offline/src/lib/__tests__/use-cacheable-section.test.tsx, yarn.lock
There was one point in the design specs I previously missed, which requires us to enable developers to programatically hide alerts:
> Warning alerts do not dismiss automatically. They *disappear if the warning conditions change* (eg. the data that wasn't loading finishes loading) or the user dismisses them _([reference](https://github.com/dhis2/design-system/blob/master/molecules/alertbar.md#warning))_
I think it could be good to discuss this PR in a call. There are a few debatable aspects to this:
- Each call to `useAlert` now corresponds to a single alert-component. Calling `show` multiple times does not show a new alert-component. However, the corresponding alert can be updated by calling `show` again with different props. I think this is more predictable behaviour, but different from …
=> feat(alerts-service): let `useAlert` return a hide function (LIBS-114)

services/offline/src/lib/__tests__/clear-sensitive-caches.test.ts, services/offline/src/lib/clear-sensitive-caches.ts
Previously, when clearSensitiveCaches didn't resolve to a relevant value, `caches.delete(key).then(() => undefined)` was returned in `Promise.all` to satisfy typescript, but I forgot to remove the `undefined` resolution when I copied in a refactor from the app platform that made `clearSensitiveCaches` resolve to a boolean indicating if any caches were deleted. Fixed that and some tests so that it resolves to the right boolean 👍
=> fix(offline): return correct value from clearSensitiveCaches

services/offline/src/lib/__tests__/clear-sensitive-caches.test.ts, services/offline/src/lib/clear-sensitive-caches.ts
=> fix(clear-caches): allow caches.keys to fail (2.x)

examples/cra/yarn.lock, examples/query-playground/yarn.lock, services/offline/src/lib/offline-interface.tsx
Relates to this app-platform [slack thread](https://dhis2.slack.com/archives/CLJSVA1RV/p1632485940049900):
Updates the 'prompt message' API so more actions can be provided to the 'Update SW' alert; the message and actions will be changed in the app platform here: https://github.com/dhis2/app-platform/pull/664
https://jira.dhis2.org/browse/LIBS-231
Both this one and the app-platform change will be back-ported to 2.37-safe branches
=> fix(offline-interface): improve sw update message API

services/data/src/react/hooks/useDataQuery.test.tsx, services/data/src/react/hooks/useDataQuery.ts
The refetch function was recreated on each render, which caused problems when it was used with refetch. If refetch was included in the useEffect dependency array the effect would run every render. By using useCallback the identity of refetch will be more stable and allow for it to be included in the dependency array again, which is recommended practice.
The identity of the refetch function will only change if you've changed the variables or changed the value of `lazy`, which seems appropriate to me. Eventually we could make it completely stable by not forking props to state, but that's a bigger change.
=> fix(use-data-query): improve stability of refetch function identity

services/data/src/links/RestAPILink/queryToRequestOptions/textPlainMatchers.test.ts, services/data/src/links/RestAPILink/queryToRequestOptions/textPlainMatchers.ts
The `@dhis2/app-service-data` package does some automatic content-type conversion. There are some text/plain matchers in place which ensure the content-type is set accordingly for specific resources. There was an error in the matcher for adding/updating an interpretation, we were treating `POST` and `PUT` requests the same, but [the docs clearly state](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-master/visualizations.html#webapi_interpretations) they are different: 
- Creating an interpretation should be done with a `POST` to `/api/interpretations/{object-type}/{object-id}` (where `object-id` actually refers to the visualisation)
- Updating an interpretation should be done with a `PUT` to `/api/interpretations/{id}` (where `id` actually refers to the interpretation) …
=> fix(data-service): identify interpretation update requests correctly

services/data/src/__tests__/integration.test.tsx, services/data/src/__tests__/mutations.test.tsx, services/data/src/react/hooks/useDataMutation.test.tsx
This adds the tests from https://github.com/dhis2/app-runtime/pull/1089. Thought I'd merge these tests beforehand so that we can be sure no existing API has broken.
The act warnings don't show up when running these tests on #1089 by the way, so I've not addressed them.
=> test(use-data-mutation): add mutation tests

services/data/src/links/RestAPILink/queryToRequestOptions/textPlainMatchers.ts
The eventVisualization is a new endpoint that will replace eventReports.
It also sends a plain text payload when creating an interpretation.
=> fix: match also eventVisualization in isCreateInterpretation

services/data/src/links/CustomDataLink.ts
Currently it is not possible to use falsey (e.g. `false`, `null`, `''`, `0`, ...) values for resources when using `CustomDataProvider`.
```jsx
// This throws the error 'No data provided for resource type <resource name>!'
<CustomDataProvider data={mockData}>
<SomeComponent />
</CustomDataProvider>
```
This PR fixes that by only treating a resource as unavailable if its value is `undefined` (when using the `CustomDataLink` link).
=> fix(custom-data-link): allow falsey values for resources

docs/types/Mutation.md, services/data/src/engine/helpers/getMutationFetchType.test.ts, services/data/src/engine/helpers/validate.test.ts, services/data/src/engine/helpers/validate.ts, services/data/src/engine/types/ExecuteOptions.ts, services/data/src/engine/types/Mutation.ts, services/data/src/links/RestAPILink.ts, services/data/src/links/RestAPILink/queryToRequestOptions.test.ts, services/data/src/links/RestAPILink/queryToRequestOptions.ts, services/data/src/links/RestAPILink/queryToRequestOptions/requestContentType.test.ts, services/data/src/links/RestAPILink/queryToRequestOptions/requestContentType.ts
This introduces JSON Patch support for the `useDataMutation` hook, via an explicit type. The `data` property needs to be a valid patch array. It is entirely up to the user to ensure this patch is valid, we do no form of validation in app-runtime.
A JSON Patch mutation object would as follows:
```js
const updateMutation = {
type: 'jsonPatch',  // The new type
resource: 'userGroups',
id: 'xyz123',
data: [ // patch array
{ op: 'replace', path: '/baz', value: 'boo' },
{ op: 'add', path: '/hello', value: ['world'] },
{ op: 'remove', path: '/foo' },
],
}
```
=> feat(data-service): add json-patch support

examples/cra/yarn.lock, examples/query-playground/yarn.lock, services/data/src/react/hooks/mergeAndCompareVariables.test.ts, services/data/src/react/hooks/mergeAndCompareVariables.ts, services/data/src/react/hooks/useDataQuery.test.tsx, services/data/src/react/hooks/useDataQuery.ts, services/data/src/react/hooks/useStaticInput.ts
- https://github.com/dhis2/app-runtime/pull/1154
- https://github.com/dhis2/app-runtime/pull/1145
Since I can't merge a failing test I've rebased 1154 on 1145. The test that fails with the code on master passes with the changes from 1154 merged in. I've updated the test a little to reflect what we want it to check with the new refetch logic.
=> fix: ensure refetch function has stable identity [LIBS-306]

services/data/src/links/RestAPILink/queryToResourcePath.test.ts, services/data/src/links/RestAPILink/queryToResourcePath.ts
Local fork of https://github.com/dhis2/app-runtime/pull/1155
=> fix: use unversioned api endpoint for tracker sub-resources

services/config/src/types.ts
Minor type update for [LIBS-176](https://dhis2.atlassian.net/browse/LIBS-176) and [LIBS-344](https://dhis2.atlassian.net/browse/LIBS-344)
=> feat: extended config type to include app name, version, and version strings

services/offline/src/lib/__tests__/clear-sensitive-caches.test.ts, services/offline/src/lib/clear-sensitive-caches.ts
Part of https://dhis2.atlassian.net/browse/LIBS-356
This PR is related to but independent of https://github.com/dhis2/app-platform/pull/757
This is in case some sensitive data ends up in the SWR cache, which is intended for files to be cached at runtime, but might end up caching something `.json` or `.action` data (though those extensions are being filtered in platform PR 757 above)
=> fix(offline): clear SWR caches betwen users [LIBS-358]

services/data/src/links/RestAPILink/queryToRequestOptions/textPlainMatchers.test.ts, services/data/src/links/RestAPILink/queryToRequestOptions/textPlainMatchers.ts
This is needed for the upcoming condition editor modal in DV.
=> fix: send POST body to indicators/expression/description as text plain

runtime/src/index.ts, services/data/src/index.ts
It's useful to export the `FetchError` class so it can be used with `instanceOf` and be extended.
=> feat(fetch-error): expose fetch-error

docs/_sidebar.md, docs/hooks/useTimeZoneConversion.md
Adds documentation for the `useTimeZoneConversion` hook.
I have tried to cover most applicable use cases without too much additional explanation.
Some other points (like javascript dates sucking and this hopefully becoming irrelevant when temporal is released) might be handled in a blog post @Topener? FYI: The original ticket ([LIBS-396](https://dhis2.atlassian.net/browse/LIBS-396)) and the [PR for the code](https://github.com/dhis2/app-runtime/pull/1308) also has a lot of background discussion. 
[LIBS-396]: https://dhis2.atlassian.net/browse/LIBS-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add documentation for useTimeZoneConversion [LIBS-396]

services/config/src/__tests__/useTimeZoneConversion.test.tsx, services/config/src/useTimeZoneConversion.ts
Implements [LIBS-490](https://dhis2.atlassian.net/browse/LIBS-490)
---
1. fixes useTimeZoneConversion hook to adjust serverOffset relative to date
---
useTimeZoneConversion hook assumes a constant offset between client and server time zones but this offset will change throughout the year depending on whether either client or server time zone observes daylight savings time.
---
-   [ ] Have written Documentation
-   This PR changes the internal implementation of the hook; the exported functions are more correct than before, but there is no change in 
-   [X] Has tests coverage
-   test has been added covering a check for client: UTC/ server: Europe/Oslo during summer time (complements existing check during standard time)
---
**A)** I have updated the hook to calculate the offset except …
=> fix: account for daylight savings time [LIBS-490]

services/data/src/engine/types/Query.ts, services/data/src/react/hooks/useDataQuery.ts
---
1. Fixes typing for onComplete data-param
---
Adds a TQueryResult type for `onComplete` in `QueryOptions`
---
=> fix(types): add generic result type to oncomplete param

runtime/package.json
Implements [LIBS-538](https://dhis2.atlassian.net/browse/LIBS-538)
---
Adds back plugin dependency that was removed when master branch was merged into alpha.
---
-   [ ] Have written Documentation
-   this is a bug fix
-   [ ] Has tests coverage
-   can be handled later as part of general work to add in tests for handling plugin wrappers (I guess testing an import of a plugin in a sample app?)
---
[LIBS-538]: https://dhis2.atlassian.net/browse/LIBS-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add back plugin service dependency [LIBS-583]

.github/workflows/dhis2-verify-lib.yml
trying to avoid the issue described here - https://github.com/orgs/community/discussions/26148#discussioncomment-3250574 which causes a PR to get stuck waiting for runs when created from an already existing branch like alpha that didn't have pushes to trigger the CI run.
=> chore: update verify-lib action to run on PRs

.github/workflows/dhis2-verify-commits.yml
revert the change to omit linting based on PR title, since it can have the side effect of a PR being merged to master with skip-release which doesn't only skip the linting, but also the release
=> chore: revert change for skipping linting commits

docs/components/Plugin.md
A recent add-on to the docs broke the Docusaurus build, this PR makes the markdown valid again and should solve the build problem.
=> docs: make markdown valid

services/data/package.json
Part of [LIBS-587](https://dhis2.atlassian.net/browse/LIBS-587); see [this comment](https://dhis2.atlassian.net/browse/LIBS-587?focusedCommentId=194633) for reasoning
To test this out, I'm thinking we can:
1. release this on alpha
2. in the app platform repo, update the `@dhis/app-runtime` dependency to alpha
3. then release an alpha of the app platform repo
4. in the d2 CLI repo, update the dependency on `@dhis2/cli-app-scripts` to the alpha version
5. release an alpha of the d2 CLI
6. then test out installing that alpha version of the CLI with npm
[LIBS-587]: https://dhis2.atlassian.net/browse/LIBS-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(deps): remove cli-app-scripts peer dep

services/data/package.json
Part of [LIBS-587](https://dhis2.atlassian.net/browse/LIBS-587)
Tested out on `alpha`, this addresses an module resolution conflict on `cli-app-scripts` and fixes an infinite loop during NPM installation of the CLI.
It seems like this dependency was introduced [here](https://github.com/dhis2/app-runtime/pull/913), which I don't think was exactly correct -- App runtime doesn’t _need_ cli-app-scripts to work, since it can be implemented independently using the `Provider` — the app adapter just breaks if it doesn’t adapt to the app-runtime changes, which seems like a typical “breaking change” rather than needing a peer dependency
This PR is to the main branch to save some PRs in the future -- `@dhis2/ui` would need to be changed to use the `alpha` branch of `app-runtime` for example, and …
=> fix(deps): remove cli-app-scripts peer dep [LIBS-587]

examples/cra/yarn.lock, examples/query-playground/package.json, examples/query-playground/src/components/Editor.css, examples/query-playground/src/components/Editor.js, examples/query-playground/src/components/Editor.module.css, examples/query-playground/src/components/QueryEditor.js, examples/query-playground/src/components/QueryResults.js, examples/query-playground/src/components/QueryTab.js, examples/query-playground/src/components/QueryTab.module.css, examples/query-playground/src/components/TabControls.js, examples/query-playground/yarn.lock, yarn.lock
Implements [LIBS-177](https://dhis2.atlassian.net/browse/LIBS-177)
The issue may be OS/font dependent -- I've never been able to reproduce it on MacOS, but Mozafar can consistently (on what I think is Ubuntu, but haven't confirmed). The reporter of the issue in Jira was using Windows. I was able to reproduce the cursor issue on MacOS by using a non-monospace font, which seems to agree with other people's experience with `brace`/`react-ace`, but I didn't find a font-related fix that worked for Mozafar.
So now this PR switches out `react-ace` for [react-codemirror](https://github.com/uiwjs/react-codemirror) to see if that fixes the issue
Uploaded here for testing: https://debug.dhis2.org/2.40dev/api/apps/query-playground/
Regarding scrolling, the behavior changed when switching to …
=> fix: query playground cursor [LIBS-177]

examples/query-playground/README.md, examples/query-playground/d2.config.js, examples/query-playground/package.json
Implements [LIBS-177](https://dhis2.atlassian.net/browse/LIBS-177)
1. Preps for publishing to App Hub by adding App Hub ID and min DHIS2 Version
2. Adds a README with release instructions
3. Adds a commit for v1.1.1
(I'm planning on merging this PR with a `merge` commit to preserve the two commits)
[LIBS-177]: https://dhis2.atlassian.net/browse/LIBS-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: v1.1.1 for query playground [LIBS-177]

services/plugin/src/Plugin.tsx
Implements [LIBS-631](https://dhis2.atlassian.net/browse/LIBS-631)
---
Moves Plugin wrapper's definition of iframe dimensions from parent div to iframe. This is equivalent, but prevents errors with highcharts visualiztion resizing in dashboard. I have tested and this does not affect the resizing logic for plugins that are supposed to auto resize.
-   [ ] Have written Documentation
-   _This change does not affect the Plugin wrapper interface, but is rather an internal implementation detail_
-   [ ] Has tests coverage
-   _No. We need to add tests for Plugin wrapper as part of work to make non-experimental_
---
[LIBS-631]: https://dhis2.atlassian.net/browse/LIBS-631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update plugin sizing definition [LIBS-631]

services/offline/src/lib/__tests__/cacheable-section-state.test.tsx, services/offline/src/lib/__tests__/use-cacheable-section.test.tsx, services/offline/src/lib/cacheable-section-state.tsx, services/offline/src/lib/cacheable-section.tsx, services/offline/src/lib/global-state-service.tsx
Implements [LIBS-642](https://dhis2.atlassian.net/browse/LIBS-642)
These hooks were implemented unoptimally, admittedly, and functions were getting recreated on each render. This caused issues if they were used as dependencies for `useEffect` hooks, like an infinite loop demoed below
I've updated the hooks to use best practices with `useCallback` and `useMemo` to make stable references and minimize unnecessary rerenders, and I added some automated tests to help verify the stability -- the tests look simplistic, but they were failing before the changes, and actually helped track down which hooks were still unstable in a TDD way
I also tested manually with the PWA example app in the App Platform, with some code that looks like an [implementation in analytics …
=> fix(cacheable-section): stable references to avoid loops [LIBS-642]

services/alerts/src/useAlert.ts
Part of [LIBS-695](https://dhis2.atlassian.net/browse/LIBS-695) -- see also the accompanying PR in the app-platform, https://github.com/dhis2/app-platform/pull/881
The change here handles the `parentAlertsAdd` function as asynchronous, since that's how post-robot [handles functions passed between windows](https://github.com/krakenjs/post-robot?tab=readme-ov-file#functions) -- it also uses optional chaining to work with previous versions of the app-shell/Plugin Loader
In the app-platform, there's just a small tweak to fix the `parentAlertsAdd` function by returning its result to the plugin
https://github.com/user-attachments/assets/4e041be2-4ae5-4c48-b134-82ad37fa5c5a
[LIBS-695]: https://dhis2.atlassian.net/browse/LIBS-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
=> fix: handle async parentAlertsAdd

services/data/src/engine/types/FetchError.ts
Noticed when using error details here: https://github.com/dhis2/reference-civil-registry-lookup/blob/069d664aa7d3c653c8a46c050c8e61d75eb327b4/civil-registry-plugin/src/LookupField/LookupField.tsx#L69-L72
This type should be flexible since details can vary, but provide some autocomplete for common properties
Here's an example `error.details` from a Route mutation:
```js
{
httpStatus: 'Not Found',
httpStatusCode: 404,
status: 'ERROR',
message: 'Route does-not-exist not found',
errorCode: 'E1005',
}
```
Some error details just end up as `{}`, as in some GET 404 responses
=> fix: expand FetchErrorDetails type

services/data/src/react/hooks/useDataQuery.ts, services/offline/src/__tests__/integration.test.tsx, services/offline/src/lib/__tests__/cacheable-section-state.test.tsx, services/offline/src/lib/__tests__/use-cacheable-section.test.tsx, services/offline/src/lib/cacheable-section.tsx
Includes fixes originally in this PR: https://github.com/dhis2/app-runtime/pull/1391
Cherry-picked from alpha-backup
=> fix: types and cacheable section fixes

runtime/package.json, services/alerts/package.json, services/config/package.json, services/data/package.json, services/offline/package.json, services/plugin/package.json
Implements [LIBS-740](https://dhis2.atlassian.net/browse/LIBS-740)
---
Adds type definition exports to package.json so that consumers can find the right types.
[LIBS-740]: https://dhis2.atlassian.net/browse/LIBS-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: reference module types in package.json export declaration [LIBS-740]

services/plugin/src/Plugin.tsx
Accidentally introduced this in 3.13.1 -- useEffect dependencies retrigger props updates, which causes unnecessary refetches in plugins
Before:
https://github.com/user-attachments/assets/fe9d9007-b83e-4ee5-a13d-4cbb719aed06
After:
https://github.com/user-attachments/assets/78d87456-1277-4a42-a8e9-67132b2d1271
=> fix(plugin): don't update props when plugin width or height props change

.github/workflows/dhis2-verify-lib.yml, services/data/src/links/RestAPILink/queryToRequestOptions/textPlainMatchers.test.ts, services/data/src/links/RestAPILink/queryToRequestOptions/textPlainMatchers.ts
1. `programIndicators/filter/description` wants a plain text payload
---
This is similar to `programIndicators/expression/description`.
---
-   [ ] Have written Documentation
-   _Not needed as this is fully internal_
-   [x] Has tests coverage
=> fix: add endpoint to text plain matchers

.github/workflows/dhis2-deploy-netlify.yml, .github/workflows/dhis2-verify-commits.yml, package.json, services/data/src/index.ts, yarn.lock
This exposes the types in Data service which are often needed by consumers of the app-runtime but currently are not exposed. This led consumers to have to do various workarounds in order to _pluck_ these types, like [this](https://github.com/dhis2/maintenance-app-beta/blob/master/src/lib/dataStore/useDataStore.ts#L11) for example.
Which this change, the types can be accessed from the top level, i.e. `import {QueryRefetchFunction} from 'dhis2/app-runtime'`
1. Instead of exporting at the top-level, I looked at exporting the types to `@dhis2/app-runtime/types`. This was mainly as I assumed that the initial intention was these types are internal, so didn't want to make them _too_ obvious. But on second thought, I thought this was unnecessary and looking at other libraries - React for instance …
=> fix: expose TS types internal to the data engine
